#!/usr/bin/env bash
# Check for command line Parameters

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# assigning paramentals to variables

path_to_file=$1
ip=$2
username=$3
path_to_shh_key=$4

# disabling strict host key checking

scp -o "StrictHostKeyChecking=no" -i "$path_t_ssh_key" "$path_to_file" "username@$ip:~/"


# checking if transfer was successful
if [ $? -eq 0 ]
then
	echo "File was Transfer Successful"
else
	echo "File Transfer Failed"
fi
